global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'anomaly_detector_serving'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['serving:8001']
